name: wasm build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/checkout@v3
      - name: Download wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-bindgen
        run: cargo install -f wasm-bindgen-cli --version 0.2.84
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Wasm-bindgen
        run: wasm-bindgen --out-dir ./docs --target web "./target/wasm32-unknown-unknown/release/invasion.wasm"
      - name: Commit wasm
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: "./docs"
